In [1]:
import numpy as np

# Path space

In [6]:
'''=============
a path with state in $n$ dim space
Input:
    dim: positive integer
    time_step: np 1-d array
================'''
class Path:
    def __init__(self,
                dim=1,
                time_step=np.linspace(0,1,11)
                ):
        self.dim = dim
        self.time_step = time_step
        self.state = np.zeros([dim, len(time_step)])
        

In [41]:
'''============
geometric average for the absolute state values
If no_initial ==1, then
    return a geometric average without the intial state
otherwise, 
    return a geometric average for all absolute value of states
no_initial =1 is particularly designed for geometric asian option
=============='''
def geometric_average(self, no_initial = 1):
    if no_initial == 1:
        arr1 = self.state[:, 1:]
    else:
        arr1 = self.state
    return np.exp(np.log(np.abs(arr1)).mean(axis = 1))        
Path.geometric_average = geometric_average

In [42]:
path1 = Path(dim = 2, time_step=np.linspace(0,2,5))
path1.state = np.random.normal(size = (path1.dim, len(path1.time_step)))

In [43]:
path1.state

array([[ 1.06091886,  0.30266103, -1.08987103,  0.45182158,  0.54675061],
       [-0.47705246, -0.35727075, -0.10614683,  0.15373971, -0.84949612]])

In [44]:
path1.geometric_average()

array([0.53428375, 0.26528518])

In [45]:
path1.geometric_average(no_initial=0)

array([0.61284974, 0.29832086])